version: '3.8'

services:
  # Database
  mysql:
    image: mysql:8.0
    container_name: veggie_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - veggie-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis for caching
  redis:
    image: redis:alpine
    container_name: veggie_redis
    ports:
      - "6379:6379"
    networks:
      - veggie-network

  # Auth Service
  auth-service:
    build: ./services/auth-service
    container_name: veggie_auth_service
    ports:
      - "${AUTH_SERVICE_PORT}:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - veggie-network
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules

networks:
  veggie-network:
    driver: bridge

volumes:
  mysql_data: