services:

  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "4000:4000"
    env_file:
      - ./services/api-gateway/.env
    depends_on:
      - auth-service
      - product-service
      - inventory-service
      - user-service
    restart: always

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    env_file:
      - ./services/auth-service/.env
    restart: always

  product-service:
    build: ./services/product-service
    container_name: product-service
    env_file:
      - ./services/product-service/.env
    restart: always

  inventory-service:
    build: ./services/inventory-service
    container_name: inventory-service
    env_file:
      - ./services/inventory-service/.env
    restart: always
  # delivery-service:
  #   build: ./services/delivery-service
  #   container_name: delivery-service
  #   env_file:
  #     - ./services/delivery-service/.env
  #   restart: always

  user-service:
    build: ./services/user-service
    container_name: user-service
    env_file:
      - ./services/user-service/.env
    restart: always

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - api-gateway
  #   restart: always
